### ISSUE TITLE
request: support for Jitsi meetings

### ISSUE THREAD

**Issue by tuxuser** [syncfast/clockwise#10]
The problem is: I wasn't able to find an API that enables you to peek at the count of participants in a meeting.

Maybe when this task is tackled: `Explore letting the clockwork zoom participant display the meeting cost.`, it could be solved, as the bot would already be participating in the meeting and could fetch the participants in that way.

**Comment by droctothorpe** [comment]
As long as Jitsi has a web client, you can extend the scrape package to handle it.

https://github.com/syncfast/clockwise/tree/master/internal/scrape

**Comment by tuxuser** [comment]
PR #11 sent.

Maybe you have some directions on how to adjust the CLI to pass in non-zoom URLs.
