### ISSUE TITLE
clockwise command not found

### ISSUE THREAD

**Issue by chovy** [syncfast/clockwise#2]
Getting this on zsh in manjaro.

**Comment by pockethook** [comment]
Have you built it with the command `go build`?

**Comment by chovyprognos** [comment]
yes, that finished without error.

**Comment by chovyprognos** [comment]
same thing on MacOS

**Comment by pockethook** [comment]
Yeah, it's not in your path. It should be in the same folder as README.md. So you can run it with `./clockwise`.

**Comment by chovy** [comment]
README? I installed with go, what do you mean?

**Comment by chovy** [comment]
have to add `$HOME/go/bin` to your path :p
